version: '3.9'

services:
  backend:
    container_name: todo_list
    build:
      context: ./TodoList
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=todo_list.postgres;Username=postgres;Password=postgres"
  
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    hostname: todo_list.postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_listDB
    volumes:
      - db_data:/var/lib/postgresql/data
    
    
volumes:
  db_data: